version: '3'
services:
  ms:
    image: management-system:latest
    build:
      context: docker/api
    container_name: management-system
    restart: always
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - /home/snail/Project/docker_data/logs:/data/logs
      - /home/snail/Project/docker_data/files:/data/files
      - /home/snail/Project/docker_data/config:/data/config

